config/routes.rb
Rails.application.routes.draw do
  root to: 'short_uris#index'

  resources :short_uris, only: [:index, :new, :create, :show]
  get '/:path', to: 'short_uris#path'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_uri.rb
class ShortUri < ApplicationRecord
  validates :original_uri, :path, presence: true
  validates :original_uri, url: true
  validates :path, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_uris_controller.rb
class ShortUrisController < ApplicationController
  def index
    @host_name = host_name
  end

  def new
    @short_uri = ShortUri.new
  end

  def create
    service = ShortUris::Creator.new(original_uri: permitted_params[:original_uri]).()
    if service.success?
      redirect_to short_uri_url(service.short_uri)
    else
      @short_uri = service.short_uri
      render 'new'
    end
  end

  def show
    @short_uri = ShortUri.find(params[:id])
  end

  def path
    service          = ShortUris::Searcher.new(path: params[:path])
    destination_path = service.call ? ShortUris::Redirecter.new(short_uri: service.short_uri).() : root_path
    redirect_to destination_path
  end

  private

  def permitted_params
    params.require(:short_uri).permit(:original_uri)
  end

  private

  def host_name
    ENV['RESOLVER_HOSTNAME']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_uris_helper.rb
module ShortUrisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-small is-primary">
      <div class="hero-body">
        <div class="container">
          <p class="title is-2">URL Shortener Service</p>
        </div>
      </div>
    </section>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/short_uris/index.html.erb
<div class="columns">
  <div class="column is-6">
    <p>
      To shorten an url <%= link_to 'click here!', new_short_uri_url %>
    </p>
  </div>
  <div class="column is-6">
    <p>
      To access a previously shorted url:
      <%= link_to "#{@host_name}/created-path", "/" %>
    </p>
  </div>
</div>

app/views/short_uris/new.html.erb
<div class="columns">
  <div class="column">
    <h3 class="title is-3">Enter a valid URL</h3>
    <h4 class="subtitle is-4">Remember to include http or https<h4>
  </div>
</div>
<div class="columns">
  <% if @short_uri.errors.any? %>
    <div class="column">
      <% @short_uri.errors.full_messages.each do |msg| %>
        <p class="help is-danger"><%= msg %></p>
      <% end %>
    </div>
  <% end %>
</div>
<div class="columns">
  <div class="column">
    <%= form_for @short_uri, url: { action: "create" } do |f| %>
      <div class="field is-grouped">
        <p class="control is-expanded">
          <%= f.text_field :original_uri, placeholder: "add your link here", class: "input" %>
        </p>
        <p class="control">
          <%= f.submit "Shorten!", class: "button is-primary" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/short_uris/show.html.erb
<div class="columns">
  <div class="column">
    <h3 class="title is-3">This is your shorted URL</h3>
    <h4 class="subtitle is-4">Check out more info below<h4>
  </div>
</div>
<div class="columns is-vcentered">
  <div class="column">
    <p>
      <strong>Original URL</strong>:
      <%= @short_uri.original_uri %>
    </p>
  </div>
  <div class="column">
    <p>
      <strong>Path</strong>:
      <%= link_to @short_uri.path, @short_uri.original_uri, target: '_blank' %>
    </p>
  </div>
  <div class="column">
    <p>
      <strong>Times Clicked</strong>:
      <%= @short_uri.times_clicked %>
    </p>
  </div>
</div>